config/routes.rb
Rails.application.routes.draw do
  root 'decks#index'
  resources :decks, except: :destroy
  resources :cards, except: %i[destroy index]
  get 'decks_review/:id', to: 'decks#review', as: 'deck_review'
  get 'decks/:deck_id/cards', to: 'cards#index', as: 'deck_cards'

  patch 'cards_batch_update' => 'decks#batch_update'

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
  scope :for_review, (-> { where(review: true) })
end

app/models/card_flip.rb
class CardFlip < ActiveRecord::Base
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards
  belongs_to :deck_collection
end

app/models/deck_collection.rb
class DeckCollection < ActiveRecord::Base
  has_many :decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  http_basic_authenticate_with name: Rails.application.secrets.basic_auth[:name], password: Rails.application.secrets.basic_auth[:password]
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @deck = Deck.find(params[:deck_id])
    @cards = @deck.cards
  end

  def new
    @card = Card.new
    @decks = Deck.all
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      flash[:success] = 'The card was successfully created'
      redirect_to decks_path
    else
      flash[:error] = 'The card had an error'
      render @card
    end
  end

  def edit
    @card = Card.find(params[:id])
    @decks = Deck.all
  end

  def update
    @card = Card.find(params[:id])
    if @card.update_attributes(card_params)
      flash[:success] = 'The card was successfully updated'
      redirect_to decks_path
    else
      flash[:error] = 'The card had an error'
      render @card
    end
  end

  def card_params
    params.require(:card).permit(:front, :back, :deck_id)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @decks = deck_collection.decks
  end

  def show
    @deck = Deck.find(params[:id])
    @cards = @deck.cards.shuffle
  end

  def review
    @deck = Deck.find(params[:id])
    @cards = @deck.cards.for_review.shuffle
    render 'show'
  end

  def new
    @deck = Deck.new
    @deck_collections = DeckCollection.all
  end

  def edit
    @deck = Deck.find(params[:id])
    @deck_collections = DeckCollection.all
  end

  def create
    @deck = Deck.new(deck_params)
    if @deck.save
      flash[:success] = 'The deck was successfully created'
      redirect_to decks_path
    else
      flash[:error] = 'The deck had an error'
      render @deck
    end
  end

  def update
    @deck = Deck.find(params[:id])
    @deck.update_attributes(deck_params)
    if @deck.save
      flash[:success] = 'The deck was successfully created'
      redirect_to decks_path
    else
      flash[:error] = 'The deck had an error'
      render @deck
    end
  end

  def batch_update
    card_flips = params[:cards][:flips]
    card_reviews = params[:cards][:reviews]
    record_flips(card_flips)
    record_reviews(card_reviews)
    if request.xhr?
      render js: "document.location = '#{root_path}'"
    else
      redirect_to root_path
    end
  end

  private

  def deck_collection
    id = params[:id] ? DeckCollection.find_by(name: params[:id]) : DeckCollection.first
  end

  def record_flips(card_flips)
    card_flips.each do |card_id, status|
      CardFlip.create(card_id: card_id,
                      status: status)
    end
  end

  def record_reviews(card_reviews)
    card_reviews.each do |card_id, new_review|
      card = Card.find(card_id)
      card.update(review: new_review) if card.review != new_review
    end
  end

  def deck_params
    params.require(:deck).permit(:name, :deck_collection_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/cards/edit.html.haml
.new-card-form
  = form_for @card do |f|

    %p
      = f.label :deck
      = f.select :deck_id, @decks.collect { |d| [d.name, d.id] }

    %p
      = f.label :front
      = f.text_field :front

    %p
      = f.label :back
      = f.text_field :back

    .button= f.submit 'Edit Card'

app/views/cards/index.html.haml
.cards-index
  %h3
    = @deck.name

  - @cards.each do |card|
    .front
      = link_to "Edit Card ##{card.id}", edit_card_path(card)
      = card.front

    .back
      %em
        = card.back
    %br

app/views/cards/new.html.haml
.new-card-form
  = form_for @card do |f|

    %p
      = f.label :deck
      = f.select :deck_id, @decks.collect { |d| [d.name, d.id] }

    %p
      = f.label :front
      = f.text_field :front

    %p
      = f.label :back
      = f.text_field :back

    .button= f.submit 'Create New Card'

app/views/decks/edit.html.haml
= form_for @deck do |f|
  = f.label :name
  = f.text_field :name

  = f.label :deck_collection
  = f.select :deck_collection_id, @deck_collections.collect { |dc| [dc.name, dc.id] }

  = f.submit 'Update Deck'

app/views/decks/index.html.haml
.actions
  = link_to 'Create New Deck', new_deck_path
  = link_to 'Create New Card', new_card_path

.decks
  - @decks.each do |deck|
    .deck
      %a{ href: deck_review_path(deck),class: 'button review' }
        REVIEW ONLY
      %a{ href: deck_path(deck), class: 'button all-cards' }
        ALL CARDS
      .description
        = "#{deck.name} (#{deck.cards.for_review.count}/#{deck.cards.count})"

      .button= link_to 'Edit Deck', edit_deck_path(deck)
      .button= link_to 'Edit Cards', deck_cards_path(deck)

app/views/decks/new.html.haml
= form_for @deck do |f|
  = f.label :name
  = f.text_field :name

  = f.label :deck_collection
  = f.select :deck_collection_id, @deck_collections.collect { |dc| [dc.name, dc.id] }

  = f.submit 'Create New Deck'

app/views/decks/show.html.haml
%h2
  .deck-name
    = @deck.name

- deck_length = @cards.length

- @cards.each_with_index do |card, index|
  .card{ class: ('hidden' unless index == 0), id: "card_#{index}" }
    %h6
      = "#{index + 1} cards of #{deck_length} total"
    .card-id.hidden
      = card.id
    .front
      %h1= card.front
    .flip
      FLIP THIS CARD
    .controls
      .right
        GOT IT
      .wrong
        MISSED IT
      .review
        = check_box_tag 'review', '1', card.review
        Review
    .back.hidden
      %h3= card.back

.submit-panel.hidden
  %h1
    Submit Panel
  .temporary-results
  .num-right
    Right:
    .num
  .num-wrong
    Wrong:
    .num
  .submit
    Submit

=javascript_include_tag 'decks'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>What are Flashcards?</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h2>
    What is Manatee?
  </h2>

  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

<%= yield %>

</body>
</html>